apiVersion: v2
name: locust-exporter
version: 0.0.2
appVersion: 0.3.0
home: https://github.com/ContainerSolutions/locust_exporter
description: A Helm chart for locust exporter
keywords:
  - locust
  - prometheus
  - monitoring
sources:
  - https://github.com/ContainerSolutions/locust_exporter
maintainers:
  - name: martinhaus
  - name: haad
engine: gotpl
type: application
annotations:
  artifacthub.io/changes: |
    - Initial helm chart changelog
